version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    labels:
      kompose.service.type: nodeport
    ports:
      - "27017:27017"
    volumes:
      - './mongo-data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=8;pwilyl

